(:name           "cdhit")
(:repo           "HermitHan/cdhit")
(:author         "KaiyuanHan")
(:version        "4.8.1")
(:intro          "CD-HIT is a very widely used program for clustering and comparing protein or nucleotide sequences.")
(:dependencies)
(:functions      "cd-hit")
